services:
    nickvergessen.newspage.controller:
        class: nickvergessen\newspage\controller\main
        arguments:
            - @auth
            - @config
            - @request
            - @template
            - @user
            - @controller.helper
            - @nickvergessen.newspage
            - %core.root_path%
            - %core.php_ext%
    nickvergessen.newspage.helper:
        class: nickvergessen\newspage\helper
        arguments:
            - @controller.helper
            - @config
    nickvergessen.newspage:
        class: nickvergessen\newspage\newspage
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @content.visibility
            - @controller.helper
            - @nickvergessen.newspage.helper
            - @pagination
            - %core.root_path%
            - %core.php_ext%
    nickvergessen.newspage.listener:
        class: nickvergessen\newspage\event\main_listener
        arguments:
            - @nickvergessen.newspage.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
