services:
    nickvergessen.newspage.controller:
        class: nickvergessen\newspage\controller\main
        arguments:
            - @config
            - @template
            - @user
            - @controller.helper
            - @nickvergessen.newspage
            - %core.root_path%
            - %core.php_ext%
    nickvergessen.newspage:
        class: nickvergessen\newspage\newspage
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @content.visibility
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
